apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validate-cronjobs-webhook
webhooks:
- name: validate-cronjobs.example.com
  rules:
  - apiGroups: ["batch"]
    apiVersions: ["v1"]
    operations: ["CREATE"]
    resources: ["cronjobs"]
  clientConfig:
    service:
      name: validate-cronjobs-webhook-service
      namespace: default
      path: "/validate-cronjobs"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVVENDQWptZ0F3SUJBZ0lVWDJvR3VBeW9XQnN2dDE4UjNWdWFlUFZIRllvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd09ERTJNRFFHQTFVRUF3d3RkbUZzYVdSaGRHVXRZM0p2Ym1wdlluTXRkMlZpYUc5dmF5MXpaWEoyYVdObApMbVJsWm1GMWJIUXVjM1pqTUI0WERUSTBNVEF4T1RFNE1UUXdPRm9YRFRJMU1UQXhPVEU0TVRRd09Gb3dPREUyCk1EUUdBMVVFQXd3dGRtRnNhV1JoZEdVdFkzSnZibXB2WW5NdGQyVmlhRzl2YXkxelpYSjJhV05sTG1SbFptRjEKYkhRdWMzWmpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXBLYU9FRWlQeTF4RQp0bFRUK09IYkhFSUFmbE9DaGJXK0lITnZ1ZVZ5MUJBWFhTSXRJS292K0JDbFI2YVloRUJ0S1g4NU1QZ1hCQzRyCnJHZFVqeXV6ZU5oMHRCcis4S2hkd1lMSHVkOXUyRHppK1FmODBuK1RKbmJBRSthT2ViRUFnUW9mREZWaHkxYncKVmIvMnJXb2ROVjJ0cEFEY2QvL3hvNmRuQlNCamlTd3lhVDlVRVFKMm9yQ0JvYVNpS05naWV4N1p3ZnRMclVyZwpSR01YSEdobGViVHRtZmZBMnh6TVFUVlZVRngxZDVlZ3dMeXlFQVBmODlyMjNWViswZHNrYnVTTXpXbi9hSnRwCkZraDlzZ0NNMHdUV3pGRlN6THQ0TDQ1OHkrTEtmKy9QVkJHcXR5TE9rUmNCSDZlSjJwOTRiVk5PdjU1dDBNbmIKODRTZG1ZWXdVUUlEQVFBQm8xTXdVVEFkQmdOVkhRNEVGZ1FVQWMramh6MHFDODRrKytsR0EzWk9VRWJvclYwdwpId1lEVlIwakJCZ3dGb0FVQWMramh6MHFDODRrKytsR0EzWk9VRWJvclYwd0R3WURWUjBUQVFIL0JBVXdBd0VCCi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFPVlFOQnA1N0tZOCttMUd6UENoQ2FqNDZUY0JjazZkbG54VWgKbXhUamgrU2hROEVtajdoZE00WkxDN2hCWGJLclVnWHdqdmFpZy9GbXBJa0VOMDF0VGx5UFIyRE5kOWhQNnFkUApPK1ZJNEYwZFZibU56Uk9NOVpyME9NS3JqdnJ6a2ZTL0I1NnkrUEppZDNKMkxoYWdqSGxlOXBCc3B1QlhQa2JGCm0wZk02QlNwenJxWkpQbzZjTDYvei82ck8vTWJDVnNLU0o5TDloZGtxYUdUQXZGb1FKcERNRElzcEFoTTdMYlMKWlRaUXBBUDcwSDZyWHR4NGhKTVNTVm1mYTBSRTlkelg4VFM3Q0FZOVJkcmtqVnhManphcmpJUm1SNEVwcHNYVQpwVzdkeGIvUmxjcDh6N3dueERuemwxdWtzR0s5aVNYRnZ1VnI3NVErNmIzazFBVXRPZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  sideEffects: None
  admissionReviewVersions: ["v1", "v1beta1"]
